config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    get 'products/search'
  end
  
  namespace :admin do
    resources :categories
    resources :products
    resources :orders
  end
  
  devise_for :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "home#index"

  namespace :api do
    get 'products/search', to: 'products#search'
  end

  resources :products, only: [:show]

  get 'admin/index', to: 'admin#index', as: :admin_index

  resources :categories, only: [:show]
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :subcategories, class_name: "Category", foreign_key: "parent_id", dependent: :destroy
  belongs_to :parent_category, class_name: "Category", optional: true, foreign_key: "parent_id"
  has_many :products, dependent: :destroy

  has_one_attached :image do |attachable|
    attachable.variant :thumb, resize_to_limit: [50, 50]
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  before_action :set_admin_category, only: %i[ show edit update destroy ]

  def index
    @admin_categories = Category.all.order(created_at: :desc)
  end

  def show
  end

  def new
    @admin_category = Category.new
  end

  def edit
  end

  def create
    @admin_category = Category.new(admin_category_params)

    respond_to do |format|
      if @admin_category.save
        format.html { redirect_to admin_category_url(@admin_category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @admin_category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin_category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @admin_category.update(admin_category_params)
        format.html { redirect_to admin_category_url(@admin_category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @admin_category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @admin_category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if @admin_category.update(admin_category_params.reject { |k| k["image"] })
      if admin_category_params["image"]
        @admin_category.image.attach(image)
      end
      redirect_to admin_products_path, notice: "Category was successfully updated"
    else
      render :edit
    end
  end

  def destroy
    @admin_category.destroy

    respond_to do |format|
      format.html { redirect_to admin_categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_admin_category
      @admin_category = Category.find(params[:id])
    end

    def admin_category_params
      params.require(:category).permit(:name, :description, :parent_id, :image)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])

    response = Faraday.get('http://localhost:3000/api/products/search', {
      category_id: @category.id,
      min: params[:min],
      max: params[:max],
      colors: params[:colors],
      sizes: params[:sizes],
      query: params[:query]
    })

    @products = JSON.parse(response.body)
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/categories/show.html.erb
<h1 class="text-center mt-4" style="font-family: 'Cinzel', serif; color: #d4af37;">Category Show Page</h1>

<div class="container mt-6">
  <div class="row">
    <div class="col-md-3">
      <div class="card mb-4" style="background-color: #343a40; border: 1px solid #d4af37;">
        <div class="card-body">
          <h5 class="card-title" style="color: #d4af37;">Filter Products</h5>
          <%= form_with url: category_path(@category), method: :get, class: "d-flex flex-column" do |form| %>
            <div class="row mb-2">
              <div class="col-6">
                <%= form.number_field :min, placeholder: "Min Price", class: "form-control" %>
              </div>
              <div class="col-6">
                <%= form.number_field :max, placeholder: "Max Price", class: "form-control" %>
              </div>
            </div>
            <%= form.text_field :colors, placeholder: "Color", class: "form-control mb-2" %>
            <%= form.text_field :sizes, placeholder: "Size", class: "form-control mb-2" %>
            <%= form.text_field :query, placeholder: "Search...", class: "form-control mb-2" %>
            <%= form.submit "Filter", class: "btn btn-dark" %>
          <% end %>
          <%= form_with url: category_path(@category), method: :get, class: "d-flex flex-column" do |form| %>
            <%= form.submit "Clear", class: "btn btn-dark mt-2" %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-md-9">
      <div class="row justify-content-center mt-6">
        <% if @products.empty? %>
          <p class="text-2xl text-left text-dark">No products found</p>
        <% else %>
          <% @products.each do |product| %>
            <div class="col-md-4 mb-4">
              <%= link_to product_path(product['id']) do %>
                <div class="card text-center" style="height: 100%;">
                  <%= image_tag(product['images'].first, class: "card-img-top rounded", style: "height: 200px; object-fit: cover;") if product['images'].present? %>
                  <div class="card-body">
                    <p class="card-text font-weight-bold text-dark"><%= product['title'] %></p>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>